<?php
/**
 * AuditLogsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Ez128\Airtable\ApiException;
use Ez128\Airtable\Configuration;
use Ez128\Airtable\FormDataProcessor;
use Ez128\Airtable\HeaderSelector;
use Ez128\Airtable\ObjectSerializer;

/**
 * AuditLogsApi Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditLogsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'auditLogEvents' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation auditLogEvents
     *
     * Audit log events
     *
     * @param  string $enterprise_account_id enterprise_account_id (required)
     * @param  string|null $start_time start_time (optional)
     * @param  string|null $end_time end_time (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsOriginatingUserIdParameter|null $originating_user_id originating_user_id (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsEventTypeParameter|null $event_type event_type (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsModelIdParameter|null $model_id model_id (optional)
     * @param  float|null $page_size page_size (optional)
     * @param  string|null $sort_order sort_order (optional)
     * @param  string|null $previous previous (optional)
     * @param  string|null $next next (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsCategoryParameter|null $category category (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['auditLogEvents'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ez128\Airtable\Model\AuditLogEvents200Response
     */
    public function auditLogEvents($enterprise_account_id, $start_time = null, $end_time = null, $originating_user_id = null, $event_type = null, $model_id = null, $page_size = null, $sort_order = null, $previous = null, $next = null, $category = null, string $contentType = self::contentTypes['auditLogEvents'][0])
    {
        list($response) = $this->auditLogEventsWithHttpInfo($enterprise_account_id, $start_time, $end_time, $originating_user_id, $event_type, $model_id, $page_size, $sort_order, $previous, $next, $category, $contentType);
        return $response;
    }

    /**
     * Operation auditLogEventsWithHttpInfo
     *
     * Audit log events
     *
     * @param  string $enterprise_account_id (required)
     * @param  string|null $start_time (optional)
     * @param  string|null $end_time (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsOriginatingUserIdParameter|null $originating_user_id (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsEventTypeParameter|null $event_type (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsModelIdParameter|null $model_id (optional)
     * @param  float|null $page_size (optional)
     * @param  string|null $sort_order (optional)
     * @param  string|null $previous (optional)
     * @param  string|null $next (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsCategoryParameter|null $category (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['auditLogEvents'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ez128\Airtable\Model\AuditLogEvents200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function auditLogEventsWithHttpInfo($enterprise_account_id, $start_time = null, $end_time = null, $originating_user_id = null, $event_type = null, $model_id = null, $page_size = null, $sort_order = null, $previous = null, $next = null, $category = null, string $contentType = self::contentTypes['auditLogEvents'][0])
    {
        $request = $this->auditLogEventsRequest($enterprise_account_id, $start_time, $end_time, $originating_user_id, $event_type, $model_id, $page_size, $sort_order, $previous, $next, $category, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ez128\Airtable\Model\AuditLogEvents200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ez128\Airtable\Model\AuditLogEvents200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ez128\Airtable\Model\AuditLogEvents200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation auditLogEventsAsync
     *
     * Audit log events
     *
     * @param  string $enterprise_account_id (required)
     * @param  string|null $start_time (optional)
     * @param  string|null $end_time (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsOriginatingUserIdParameter|null $originating_user_id (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsEventTypeParameter|null $event_type (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsModelIdParameter|null $model_id (optional)
     * @param  float|null $page_size (optional)
     * @param  string|null $sort_order (optional)
     * @param  string|null $previous (optional)
     * @param  string|null $next (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsCategoryParameter|null $category (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['auditLogEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditLogEventsAsync($enterprise_account_id, $start_time = null, $end_time = null, $originating_user_id = null, $event_type = null, $model_id = null, $page_size = null, $sort_order = null, $previous = null, $next = null, $category = null, string $contentType = self::contentTypes['auditLogEvents'][0])
    {
        return $this->auditLogEventsAsyncWithHttpInfo($enterprise_account_id, $start_time, $end_time, $originating_user_id, $event_type, $model_id, $page_size, $sort_order, $previous, $next, $category, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation auditLogEventsAsyncWithHttpInfo
     *
     * Audit log events
     *
     * @param  string $enterprise_account_id (required)
     * @param  string|null $start_time (optional)
     * @param  string|null $end_time (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsOriginatingUserIdParameter|null $originating_user_id (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsEventTypeParameter|null $event_type (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsModelIdParameter|null $model_id (optional)
     * @param  float|null $page_size (optional)
     * @param  string|null $sort_order (optional)
     * @param  string|null $previous (optional)
     * @param  string|null $next (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsCategoryParameter|null $category (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['auditLogEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditLogEventsAsyncWithHttpInfo($enterprise_account_id, $start_time = null, $end_time = null, $originating_user_id = null, $event_type = null, $model_id = null, $page_size = null, $sort_order = null, $previous = null, $next = null, $category = null, string $contentType = self::contentTypes['auditLogEvents'][0])
    {
        $returnType = '\Ez128\Airtable\Model\AuditLogEvents200Response';
        $request = $this->auditLogEventsRequest($enterprise_account_id, $start_time, $end_time, $originating_user_id, $event_type, $model_id, $page_size, $sort_order, $previous, $next, $category, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auditLogEvents'
     *
     * @param  string $enterprise_account_id (required)
     * @param  string|null $start_time (optional)
     * @param  string|null $end_time (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsOriginatingUserIdParameter|null $originating_user_id (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsEventTypeParameter|null $event_type (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsModelIdParameter|null $model_id (optional)
     * @param  float|null $page_size (optional)
     * @param  string|null $sort_order (optional)
     * @param  string|null $previous (optional)
     * @param  string|null $next (optional)
     * @param  \Ez128\Airtable\Model\AuditLogEventsCategoryParameter|null $category (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['auditLogEvents'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function auditLogEventsRequest($enterprise_account_id, $start_time = null, $end_time = null, $originating_user_id = null, $event_type = null, $model_id = null, $page_size = null, $sort_order = null, $previous = null, $next = null, $category = null, string $contentType = self::contentTypes['auditLogEvents'][0])
    {

        // verify the required parameter 'enterprise_account_id' is set
        if ($enterprise_account_id === null || (is_array($enterprise_account_id) && count($enterprise_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $enterprise_account_id when calling auditLogEvents'
            );
        }
        if (!preg_match("/ent[0-9a-zA-Z]{14}$/", $enterprise_account_id)) {
            throw new \InvalidArgumentException("invalid value for \"enterprise_account_id\" when calling AuditLogsApi.auditLogEvents, must conform to the pattern /ent[0-9a-zA-Z]{14}$/.");
        }
        











        $resourcePath = '/v0/meta/enterpriseAccounts/{enterpriseAccountId}/auditLogEvents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_time,
            'startTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_time,
            'endTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $originating_user_id,
            'originatingUserId', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $event_type,
            'eventType', // param base name
            'anyOf&lt;Audit-log-event-types,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $model_id,
            'modelId', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_order,
            'sortOrder', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $previous,
            'previous', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $next,
            'next', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $category,
            'category', // param base name
            'anyOf&lt;string,array&gt;', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($enterprise_account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'enterpriseAccountId' . '}',
                ObjectSerializer::toPathValue($enterprise_account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
