<?php
/**
 * CommentApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Ez128\Airtable\ApiException;
use Ez128\Airtable\Configuration;
use Ez128\Airtable\FormDataProcessor;
use Ez128\Airtable\HeaderSelector;
use Ez128\Airtable\ObjectSerializer;

/**
 * CommentApi Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createComment' => [
            'application/json',
        ],
        'deleteComment' => [
            'application/json',
        ],
        'listComments' => [
            'application/json',
        ],
        'updateComment' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createComment
     *
     * Create comment
     *
     * @param  string $base_id base_id (required)
     * @param  string $table_id_or_name table_id_or_name (required)
     * @param  string $record_id record_id (required)
     * @param  \Ez128\Airtable\Model\CreateCommentRequest|null $create_comment_request create_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ez128\Airtable\Model\CreateComment200Response
     */
    public function createComment($base_id, $table_id_or_name, $record_id, $create_comment_request = null, string $contentType = self::contentTypes['createComment'][0])
    {
        list($response) = $this->createCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $create_comment_request, $contentType);
        return $response;
    }

    /**
     * Operation createCommentWithHttpInfo
     *
     * Create comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  \Ez128\Airtable\Model\CreateCommentRequest|null $create_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ez128\Airtable\Model\CreateComment200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function createCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $create_comment_request = null, string $contentType = self::contentTypes['createComment'][0])
    {
        $request = $this->createCommentRequest($base_id, $table_id_or_name, $record_id, $create_comment_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ez128\Airtable\Model\CreateComment200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ez128\Airtable\Model\CreateComment200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ez128\Airtable\Model\CreateComment200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createCommentAsync
     *
     * Create comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  \Ez128\Airtable\Model\CreateCommentRequest|null $create_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCommentAsync($base_id, $table_id_or_name, $record_id, $create_comment_request = null, string $contentType = self::contentTypes['createComment'][0])
    {
        return $this->createCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $create_comment_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createCommentAsyncWithHttpInfo
     *
     * Create comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  \Ez128\Airtable\Model\CreateCommentRequest|null $create_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $create_comment_request = null, string $contentType = self::contentTypes['createComment'][0])
    {
        $returnType = '\Ez128\Airtable\Model\CreateComment200Response';
        $request = $this->createCommentRequest($base_id, $table_id_or_name, $record_id, $create_comment_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createComment'
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  \Ez128\Airtable\Model\CreateCommentRequest|null $create_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createCommentRequest($base_id, $table_id_or_name, $record_id, $create_comment_request = null, string $contentType = self::contentTypes['createComment'][0])
    {

        // verify the required parameter 'base_id' is set
        if ($base_id === null || (is_array($base_id) && count($base_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $base_id when calling createComment'
            );
        }
        if (!preg_match("/app[0-9a-zA-Z]{14}$/", $base_id)) {
            throw new \InvalidArgumentException("invalid value for \"base_id\" when calling CommentApi.createComment, must conform to the pattern /app[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'table_id_or_name' is set
        if ($table_id_or_name === null || (is_array($table_id_or_name) && count($table_id_or_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $table_id_or_name when calling createComment'
            );
        }
        if (!preg_match("/[^\/]+$/", $table_id_or_name)) {
            throw new \InvalidArgumentException("invalid value for \"table_id_or_name\" when calling CommentApi.createComment, must conform to the pattern /[^\/]+$/.");
        }
        
        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling createComment'
            );
        }
        if (!preg_match("/rec[0-9a-zA-Z]{14}$/", $record_id)) {
            throw new \InvalidArgumentException("invalid value for \"record_id\" when calling CommentApi.createComment, must conform to the pattern /rec[0-9a-zA-Z]{14}$/.");
        }
        


        $resourcePath = '/v0/{baseId}/{tableIdOrName}/{recordId}/comments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($base_id !== null) {
            $resourcePath = str_replace(
                '{' . 'baseId' . '}',
                ObjectSerializer::toPathValue($base_id),
                $resourcePath
            );
        }
        // path params
        if ($table_id_or_name !== null) {
            $resourcePath = str_replace(
                '{' . 'tableIdOrName' . '}',
                ObjectSerializer::toPathValue($table_id_or_name),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_comment_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_comment_request));
            } else {
                $httpBody = $create_comment_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteComment
     *
     * Delete comment
     *
     * @param  string $base_id base_id (required)
     * @param  string $table_id_or_name table_id_or_name (required)
     * @param  string $record_id record_id (required)
     * @param  string $row_comment_id row_comment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ez128\Airtable\Model\DeleteComment200Response
     */
    public function deleteComment($base_id, $table_id_or_name, $record_id, $row_comment_id, string $contentType = self::contentTypes['deleteComment'][0])
    {
        list($response) = $this->deleteCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $contentType);
        return $response;
    }

    /**
     * Operation deleteCommentWithHttpInfo
     *
     * Delete comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ez128\Airtable\Model\DeleteComment200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, string $contentType = self::contentTypes['deleteComment'][0])
    {
        $request = $this->deleteCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ez128\Airtable\Model\DeleteComment200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ez128\Airtable\Model\DeleteComment200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ez128\Airtable\Model\DeleteComment200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteCommentAsync
     *
     * Delete comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCommentAsync($base_id, $table_id_or_name, $record_id, $row_comment_id, string $contentType = self::contentTypes['deleteComment'][0])
    {
        return $this->deleteCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteCommentAsyncWithHttpInfo
     *
     * Delete comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, string $contentType = self::contentTypes['deleteComment'][0])
    {
        $returnType = '\Ez128\Airtable\Model\DeleteComment200Response';
        $request = $this->deleteCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteComment'
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, string $contentType = self::contentTypes['deleteComment'][0])
    {

        // verify the required parameter 'base_id' is set
        if ($base_id === null || (is_array($base_id) && count($base_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $base_id when calling deleteComment'
            );
        }
        if (!preg_match("/app[0-9a-zA-Z]{14}$/", $base_id)) {
            throw new \InvalidArgumentException("invalid value for \"base_id\" when calling CommentApi.deleteComment, must conform to the pattern /app[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'table_id_or_name' is set
        if ($table_id_or_name === null || (is_array($table_id_or_name) && count($table_id_or_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $table_id_or_name when calling deleteComment'
            );
        }
        if (!preg_match("/[^\/]+$/", $table_id_or_name)) {
            throw new \InvalidArgumentException("invalid value for \"table_id_or_name\" when calling CommentApi.deleteComment, must conform to the pattern /[^\/]+$/.");
        }
        
        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling deleteComment'
            );
        }
        if (!preg_match("/rec[0-9a-zA-Z]{14}$/", $record_id)) {
            throw new \InvalidArgumentException("invalid value for \"record_id\" when calling CommentApi.deleteComment, must conform to the pattern /rec[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'row_comment_id' is set
        if ($row_comment_id === null || (is_array($row_comment_id) && count($row_comment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $row_comment_id when calling deleteComment'
            );
        }
        if (!preg_match("/com[0-9a-zA-Z]{14}$/", $row_comment_id)) {
            throw new \InvalidArgumentException("invalid value for \"row_comment_id\" when calling CommentApi.deleteComment, must conform to the pattern /com[0-9a-zA-Z]{14}$/.");
        }
        

        $resourcePath = '/v0/{baseId}/{tableIdOrName}/{recordId}/comments/{rowCommentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($base_id !== null) {
            $resourcePath = str_replace(
                '{' . 'baseId' . '}',
                ObjectSerializer::toPathValue($base_id),
                $resourcePath
            );
        }
        // path params
        if ($table_id_or_name !== null) {
            $resourcePath = str_replace(
                '{' . 'tableIdOrName' . '}',
                ObjectSerializer::toPathValue($table_id_or_name),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }
        // path params
        if ($row_comment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'rowCommentId' . '}',
                ObjectSerializer::toPathValue($row_comment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listComments
     *
     * List comments
     *
     * @param  string $base_id base_id (required)
     * @param  string $table_id_or_name table_id_or_name (required)
     * @param  string $record_id record_id (required)
     * @param  float|null $page_size page_size (optional)
     * @param  string|null $offset offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listComments'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ez128\Airtable\Model\ListComments200Response
     */
    public function listComments($base_id, $table_id_or_name, $record_id, $page_size = null, $offset = null, string $contentType = self::contentTypes['listComments'][0])
    {
        list($response) = $this->listCommentsWithHttpInfo($base_id, $table_id_or_name, $record_id, $page_size, $offset, $contentType);
        return $response;
    }

    /**
     * Operation listCommentsWithHttpInfo
     *
     * List comments
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  float|null $page_size (optional)
     * @param  string|null $offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listComments'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ez128\Airtable\Model\ListComments200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCommentsWithHttpInfo($base_id, $table_id_or_name, $record_id, $page_size = null, $offset = null, string $contentType = self::contentTypes['listComments'][0])
    {
        $request = $this->listCommentsRequest($base_id, $table_id_or_name, $record_id, $page_size, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ez128\Airtable\Model\ListComments200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ez128\Airtable\Model\ListComments200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ez128\Airtable\Model\ListComments200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCommentsAsync
     *
     * List comments
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  float|null $page_size (optional)
     * @param  string|null $offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listComments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCommentsAsync($base_id, $table_id_or_name, $record_id, $page_size = null, $offset = null, string $contentType = self::contentTypes['listComments'][0])
    {
        return $this->listCommentsAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $page_size, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCommentsAsyncWithHttpInfo
     *
     * List comments
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  float|null $page_size (optional)
     * @param  string|null $offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listComments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listCommentsAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $page_size = null, $offset = null, string $contentType = self::contentTypes['listComments'][0])
    {
        $returnType = '\Ez128\Airtable\Model\ListComments200Response';
        $request = $this->listCommentsRequest($base_id, $table_id_or_name, $record_id, $page_size, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listComments'
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  float|null $page_size (optional)
     * @param  string|null $offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listComments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listCommentsRequest($base_id, $table_id_or_name, $record_id, $page_size = null, $offset = null, string $contentType = self::contentTypes['listComments'][0])
    {

        // verify the required parameter 'base_id' is set
        if ($base_id === null || (is_array($base_id) && count($base_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $base_id when calling listComments'
            );
        }
        if (!preg_match("/app[0-9a-zA-Z]{14}$/", $base_id)) {
            throw new \InvalidArgumentException("invalid value for \"base_id\" when calling CommentApi.listComments, must conform to the pattern /app[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'table_id_or_name' is set
        if ($table_id_or_name === null || (is_array($table_id_or_name) && count($table_id_or_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $table_id_or_name when calling listComments'
            );
        }
        if (!preg_match("/[^\/]+$/", $table_id_or_name)) {
            throw new \InvalidArgumentException("invalid value for \"table_id_or_name\" when calling CommentApi.listComments, must conform to the pattern /[^\/]+$/.");
        }
        
        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling listComments'
            );
        }
        if (!preg_match("/rec[0-9a-zA-Z]{14}$/", $record_id)) {
            throw new \InvalidArgumentException("invalid value for \"record_id\" when calling CommentApi.listComments, must conform to the pattern /rec[0-9a-zA-Z]{14}$/.");
        }
        



        $resourcePath = '/v0/{baseId}/{tableIdOrName}/{recordId}/comments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($base_id !== null) {
            $resourcePath = str_replace(
                '{' . 'baseId' . '}',
                ObjectSerializer::toPathValue($base_id),
                $resourcePath
            );
        }
        // path params
        if ($table_id_or_name !== null) {
            $resourcePath = str_replace(
                '{' . 'tableIdOrName' . '}',
                ObjectSerializer::toPathValue($table_id_or_name),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateComment
     *
     * Update comment
     *
     * @param  string $base_id base_id (required)
     * @param  string $table_id_or_name table_id_or_name (required)
     * @param  string $record_id record_id (required)
     * @param  string $row_comment_id row_comment_id (required)
     * @param  \Ez128\Airtable\Model\UpdateCommentRequest|null $update_comment_request update_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Ez128\Airtable\Model\CreateComment200Response
     */
    public function updateComment($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request = null, string $contentType = self::contentTypes['updateComment'][0])
    {
        list($response) = $this->updateCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request, $contentType);
        return $response;
    }

    /**
     * Operation updateCommentWithHttpInfo
     *
     * Update comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  \Ez128\Airtable\Model\UpdateCommentRequest|null $update_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateComment'] to see the possible values for this operation
     *
     * @throws \Ez128\Airtable\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Ez128\Airtable\Model\CreateComment200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateCommentWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request = null, string $contentType = self::contentTypes['updateComment'][0])
    {
        $request = $this->updateCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Ez128\Airtable\Model\CreateComment200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Ez128\Airtable\Model\CreateComment200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Ez128\Airtable\Model\CreateComment200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateCommentAsync
     *
     * Update comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  \Ez128\Airtable\Model\UpdateCommentRequest|null $update_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateCommentAsync($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request = null, string $contentType = self::contentTypes['updateComment'][0])
    {
        return $this->updateCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateCommentAsyncWithHttpInfo
     *
     * Update comment
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  \Ez128\Airtable\Model\UpdateCommentRequest|null $update_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateCommentAsyncWithHttpInfo($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request = null, string $contentType = self::contentTypes['updateComment'][0])
    {
        $returnType = '\Ez128\Airtable\Model\CreateComment200Response';
        $request = $this->updateCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateComment'
     *
     * @param  string $base_id (required)
     * @param  string $table_id_or_name (required)
     * @param  string $record_id (required)
     * @param  string $row_comment_id (required)
     * @param  \Ez128\Airtable\Model\UpdateCommentRequest|null $update_comment_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateComment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateCommentRequest($base_id, $table_id_or_name, $record_id, $row_comment_id, $update_comment_request = null, string $contentType = self::contentTypes['updateComment'][0])
    {

        // verify the required parameter 'base_id' is set
        if ($base_id === null || (is_array($base_id) && count($base_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $base_id when calling updateComment'
            );
        }
        if (!preg_match("/app[0-9a-zA-Z]{14}$/", $base_id)) {
            throw new \InvalidArgumentException("invalid value for \"base_id\" when calling CommentApi.updateComment, must conform to the pattern /app[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'table_id_or_name' is set
        if ($table_id_or_name === null || (is_array($table_id_or_name) && count($table_id_or_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $table_id_or_name when calling updateComment'
            );
        }
        if (!preg_match("/[^\/]+$/", $table_id_or_name)) {
            throw new \InvalidArgumentException("invalid value for \"table_id_or_name\" when calling CommentApi.updateComment, must conform to the pattern /[^\/]+$/.");
        }
        
        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling updateComment'
            );
        }
        if (!preg_match("/rec[0-9a-zA-Z]{14}$/", $record_id)) {
            throw new \InvalidArgumentException("invalid value for \"record_id\" when calling CommentApi.updateComment, must conform to the pattern /rec[0-9a-zA-Z]{14}$/.");
        }
        
        // verify the required parameter 'row_comment_id' is set
        if ($row_comment_id === null || (is_array($row_comment_id) && count($row_comment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $row_comment_id when calling updateComment'
            );
        }
        if (!preg_match("/com[0-9a-zA-Z]{14}$/", $row_comment_id)) {
            throw new \InvalidArgumentException("invalid value for \"row_comment_id\" when calling CommentApi.updateComment, must conform to the pattern /com[0-9a-zA-Z]{14}$/.");
        }
        


        $resourcePath = '/v0/{baseId}/{tableIdOrName}/{recordId}/comments/{rowCommentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($base_id !== null) {
            $resourcePath = str_replace(
                '{' . 'baseId' . '}',
                ObjectSerializer::toPathValue($base_id),
                $resourcePath
            );
        }
        // path params
        if ($table_id_or_name !== null) {
            $resourcePath = str_replace(
                '{' . 'tableIdOrName' . '}',
                ObjectSerializer::toPathValue($table_id_or_name),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }
        // path params
        if ($row_comment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'rowCommentId' . '}',
                ObjectSerializer::toPathValue($row_comment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_comment_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_comment_request));
            } else {
                $httpBody = $update_comment_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
