<?php
/**
 * AuditLogEvents200ResponseEventsInnerContext
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Model;

use \ArrayAccess;
use \Ez128\Airtable\ObjectSerializer;

/**
 * AuditLogEvents200ResponseEventsInnerContext Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AuditLogEvents200ResponseEventsInnerContext implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'audit_log_events_200_response_events_inner_context';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'action_id' => 'string',
        'base_id' => 'string',
        'descendant_enterprise_account_id' => 'string',
        'enterprise_account_id' => 'string',
        'interface_id' => 'string',
        'workspace_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'action_id' => null,
        'base_id' => null,
        'descendant_enterprise_account_id' => null,
        'enterprise_account_id' => null,
        'interface_id' => null,
        'workspace_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'action_id' => false,
        'base_id' => false,
        'descendant_enterprise_account_id' => false,
        'enterprise_account_id' => false,
        'interface_id' => false,
        'workspace_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'action_id' => 'actionId',
        'base_id' => 'baseId',
        'descendant_enterprise_account_id' => 'descendantEnterpriseAccountId',
        'enterprise_account_id' => 'enterpriseAccountId',
        'interface_id' => 'interfaceId',
        'workspace_id' => 'workspaceId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'action_id' => 'setActionId',
        'base_id' => 'setBaseId',
        'descendant_enterprise_account_id' => 'setDescendantEnterpriseAccountId',
        'enterprise_account_id' => 'setEnterpriseAccountId',
        'interface_id' => 'setInterfaceId',
        'workspace_id' => 'setWorkspaceId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'action_id' => 'getActionId',
        'base_id' => 'getBaseId',
        'descendant_enterprise_account_id' => 'getDescendantEnterpriseAccountId',
        'enterprise_account_id' => 'getEnterpriseAccountId',
        'interface_id' => 'getInterfaceId',
        'workspace_id' => 'getWorkspaceId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('action_id', $data ?? [], null);
        $this->setIfExists('base_id', $data ?? [], null);
        $this->setIfExists('descendant_enterprise_account_id', $data ?? [], null);
        $this->setIfExists('enterprise_account_id', $data ?? [], null);
        $this->setIfExists('interface_id', $data ?? [], null);
        $this->setIfExists('workspace_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['action_id'] === null) {
            $invalidProperties[] = "'action_id' can't be null";
        }
        if ($this->container['enterprise_account_id'] === null) {
            $invalidProperties[] = "'enterprise_account_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets action_id
     *
     * @return string
     */
    public function getActionId()
    {
        return $this->container['action_id'];
    }

    /**
     * Sets action_id
     *
     * @param string $action_id action_id
     *
     * @return self
     */
    public function setActionId($action_id)
    {
        if (is_null($action_id)) {
            throw new \InvalidArgumentException('non-nullable action_id cannot be null');
        }
        $this->container['action_id'] = $action_id;

        return $this;
    }

    /**
     * Gets base_id
     *
     * @return string|null
     */
    public function getBaseId()
    {
        return $this->container['base_id'];
    }

    /**
     * Sets base_id
     *
     * @param string|null $base_id Base ID, a unique identifier for a base.
     *
     * @return self
     */
    public function setBaseId($base_id)
    {
        if (is_null($base_id)) {
            throw new \InvalidArgumentException('non-nullable base_id cannot be null');
        }
        $this->container['base_id'] = $base_id;

        return $this;
    }

    /**
     * Gets descendant_enterprise_account_id
     *
     * @return string|null
     */
    public function getDescendantEnterpriseAccountId()
    {
        return $this->container['descendant_enterprise_account_id'];
    }

    /**
     * Sets descendant_enterprise_account_id
     *
     * @param string|null $descendant_enterprise_account_id descendant_enterprise_account_id
     *
     * @return self
     */
    public function setDescendantEnterpriseAccountId($descendant_enterprise_account_id)
    {
        if (is_null($descendant_enterprise_account_id)) {
            throw new \InvalidArgumentException('non-nullable descendant_enterprise_account_id cannot be null');
        }
        $this->container['descendant_enterprise_account_id'] = $descendant_enterprise_account_id;

        return $this;
    }

    /**
     * Gets enterprise_account_id
     *
     * @return string
     */
    public function getEnterpriseAccountId()
    {
        return $this->container['enterprise_account_id'];
    }

    /**
     * Sets enterprise_account_id
     *
     * @param string $enterprise_account_id enterprise_account_id
     *
     * @return self
     */
    public function setEnterpriseAccountId($enterprise_account_id)
    {
        if (is_null($enterprise_account_id)) {
            throw new \InvalidArgumentException('non-nullable enterprise_account_id cannot be null');
        }
        $this->container['enterprise_account_id'] = $enterprise_account_id;

        return $this;
    }

    /**
     * Gets interface_id
     *
     * @return string|null
     */
    public function getInterfaceId()
    {
        return $this->container['interface_id'];
    }

    /**
     * Sets interface_id
     *
     * @param string|null $interface_id interface_id
     *
     * @return self
     */
    public function setInterfaceId($interface_id)
    {
        if (is_null($interface_id)) {
            throw new \InvalidArgumentException('non-nullable interface_id cannot be null');
        }
        $this->container['interface_id'] = $interface_id;

        return $this;
    }

    /**
     * Gets workspace_id
     *
     * @return string|null
     */
    public function getWorkspaceId()
    {
        return $this->container['workspace_id'];
    }

    /**
     * Sets workspace_id
     *
     * @param string|null $workspace_id workspace_id
     *
     * @return self
     */
    public function setWorkspaceId($workspace_id)
    {
        if (is_null($workspace_id)) {
            throw new \InvalidArgumentException('non-nullable workspace_id cannot be null');
        }
        $this->container['workspace_id'] = $workspace_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


