<?php
/**
 * HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Model;

use \ArrayAccess;
use \Ez128\Airtable\ObjectSerializer;

/**
 * HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponse Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'hyperdb_upsert_records_by_primary_keys_200_response_compressedResponseDataResultPromise_anyOf_value_compressedResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bytes_per_element' => 'float',
        'buffer' => '\Ez128\Airtable\Model\HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponseBuffer',
        'byte_length' => 'float',
        'byte_offset' => 'float',
        'length' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bytes_per_element' => null,
        'buffer' => null,
        'byte_length' => null,
        'byte_offset' => null,
        'length' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bytes_per_element' => false,
        'buffer' => false,
        'byte_length' => false,
        'byte_offset' => false,
        'length' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bytes_per_element' => 'BYTES_PER_ELEMENT',
        'buffer' => 'buffer',
        'byte_length' => 'byteLength',
        'byte_offset' => 'byteOffset',
        'length' => 'length'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bytes_per_element' => 'setBytesPerElement',
        'buffer' => 'setBuffer',
        'byte_length' => 'setByteLength',
        'byte_offset' => 'setByteOffset',
        'length' => 'setLength'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bytes_per_element' => 'getBytesPerElement',
        'buffer' => 'getBuffer',
        'byte_length' => 'getByteLength',
        'byte_offset' => 'getByteOffset',
        'length' => 'getLength'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bytes_per_element', $data ?? [], null);
        $this->setIfExists('buffer', $data ?? [], null);
        $this->setIfExists('byte_length', $data ?? [], null);
        $this->setIfExists('byte_offset', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bytes_per_element'] === null) {
            $invalidProperties[] = "'bytes_per_element' can't be null";
        }
        if ($this->container['buffer'] === null) {
            $invalidProperties[] = "'buffer' can't be null";
        }
        if ($this->container['byte_length'] === null) {
            $invalidProperties[] = "'byte_length' can't be null";
        }
        if ($this->container['byte_offset'] === null) {
            $invalidProperties[] = "'byte_offset' can't be null";
        }
        if ($this->container['length'] === null) {
            $invalidProperties[] = "'length' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bytes_per_element
     *
     * @return float
     */
    public function getBytesPerElement()
    {
        return $this->container['bytes_per_element'];
    }

    /**
     * Sets bytes_per_element
     *
     * @param float $bytes_per_element bytes_per_element
     *
     * @return self
     */
    public function setBytesPerElement($bytes_per_element)
    {
        if (is_null($bytes_per_element)) {
            throw new \InvalidArgumentException('non-nullable bytes_per_element cannot be null');
        }
        $this->container['bytes_per_element'] = $bytes_per_element;

        return $this;
    }

    /**
     * Gets buffer
     *
     * @return \Ez128\Airtable\Model\HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponseBuffer
     */
    public function getBuffer()
    {
        return $this->container['buffer'];
    }

    /**
     * Sets buffer
     *
     * @param \Ez128\Airtable\Model\HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOfValueCompressedResponseBuffer $buffer buffer
     *
     * @return self
     */
    public function setBuffer($buffer)
    {
        if (is_null($buffer)) {
            throw new \InvalidArgumentException('non-nullable buffer cannot be null');
        }
        $this->container['buffer'] = $buffer;

        return $this;
    }

    /**
     * Gets byte_length
     *
     * @return float
     */
    public function getByteLength()
    {
        return $this->container['byte_length'];
    }

    /**
     * Sets byte_length
     *
     * @param float $byte_length byte_length
     *
     * @return self
     */
    public function setByteLength($byte_length)
    {
        if (is_null($byte_length)) {
            throw new \InvalidArgumentException('non-nullable byte_length cannot be null');
        }
        $this->container['byte_length'] = $byte_length;

        return $this;
    }

    /**
     * Gets byte_offset
     *
     * @return float
     */
    public function getByteOffset()
    {
        return $this->container['byte_offset'];
    }

    /**
     * Sets byte_offset
     *
     * @param float $byte_offset byte_offset
     *
     * @return self
     */
    public function setByteOffset($byte_offset)
    {
        if (is_null($byte_offset)) {
            throw new \InvalidArgumentException('non-nullable byte_offset cannot be null');
        }
        $this->container['byte_offset'] = $byte_offset;

        return $this;
    }

    /**
     * Gets length
     *
     * @return float
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param float $length length
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


