<?php
/**
 * UpdateWorkspaceRestrictionsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Model;

use \ArrayAccess;
use \Ez128\Airtable\ObjectSerializer;

/**
 * UpdateWorkspaceRestrictionsRequest Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateWorkspaceRestrictionsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'update_workspace_restrictions_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'invite_creation_restriction' => 'string',
        'share_creation_restriction' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'invite_creation_restriction' => null,
        'share_creation_restriction' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'invite_creation_restriction' => false,
        'share_creation_restriction' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'invite_creation_restriction' => 'inviteCreationRestriction',
        'share_creation_restriction' => 'shareCreationRestriction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'invite_creation_restriction' => 'setInviteCreationRestriction',
        'share_creation_restriction' => 'setShareCreationRestriction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'invite_creation_restriction' => 'getInviteCreationRestriction',
        'share_creation_restriction' => 'getShareCreationRestriction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INVITE_CREATION_RESTRICTION_UNRESTRICTED = 'unrestricted';
    public const INVITE_CREATION_RESTRICTION_ONLY_OWNERS = 'onlyOwners';
    public const SHARE_CREATION_RESTRICTION_UNRESTRICTED = 'unrestricted';
    public const SHARE_CREATION_RESTRICTION_ONLY_OWNERS = 'onlyOwners';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInviteCreationRestrictionAllowableValues()
    {
        return [
            self::INVITE_CREATION_RESTRICTION_UNRESTRICTED,
            self::INVITE_CREATION_RESTRICTION_ONLY_OWNERS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getShareCreationRestrictionAllowableValues()
    {
        return [
            self::SHARE_CREATION_RESTRICTION_UNRESTRICTED,
            self::SHARE_CREATION_RESTRICTION_ONLY_OWNERS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('invite_creation_restriction', $data ?? [], null);
        $this->setIfExists('share_creation_restriction', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getInviteCreationRestrictionAllowableValues();
        if (!is_null($this->container['invite_creation_restriction']) && !in_array($this->container['invite_creation_restriction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'invite_creation_restriction', must be one of '%s'",
                $this->container['invite_creation_restriction'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getShareCreationRestrictionAllowableValues();
        if (!is_null($this->container['share_creation_restriction']) && !in_array($this->container['share_creation_restriction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'share_creation_restriction', must be one of '%s'",
                $this->container['share_creation_restriction'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invite_creation_restriction
     *
     * @return string|null
     */
    public function getInviteCreationRestriction()
    {
        return $this->container['invite_creation_restriction'];
    }

    /**
     * Sets invite_creation_restriction
     *
     * @param string|null $invite_creation_restriction invite_creation_restriction
     *
     * @return self
     */
    public function setInviteCreationRestriction($invite_creation_restriction)
    {
        if (is_null($invite_creation_restriction)) {
            throw new \InvalidArgumentException('non-nullable invite_creation_restriction cannot be null');
        }
        $allowedValues = $this->getInviteCreationRestrictionAllowableValues();
        if (!in_array($invite_creation_restriction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'invite_creation_restriction', must be one of '%s'",
                    $invite_creation_restriction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['invite_creation_restriction'] = $invite_creation_restriction;

        return $this;
    }

    /**
     * Gets share_creation_restriction
     *
     * @return string|null
     */
    public function getShareCreationRestriction()
    {
        return $this->container['share_creation_restriction'];
    }

    /**
     * Sets share_creation_restriction
     *
     * @param string|null $share_creation_restriction share_creation_restriction
     *
     * @return self
     */
    public function setShareCreationRestriction($share_creation_restriction)
    {
        if (is_null($share_creation_restriction)) {
            throw new \InvalidArgumentException('non-nullable share_creation_restriction cannot be null');
        }
        $allowedValues = $this->getShareCreationRestrictionAllowableValues();
        if (!in_array($share_creation_restriction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'share_creation_restriction', must be one of '%s'",
                    $share_creation_restriction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['share_creation_restriction'] = $share_creation_restriction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


