<?php
/**
 * WebhooksSpecificationIncludes
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ez128\Airtable\Model;

use \ArrayAccess;
use \Ez128\Airtable\ObjectSerializer;

/**
 * WebhooksSpecificationIncludes Class Doc Comment
 *
 * @category Class
 * @description By default, the payloads only contain the data that changed. In order to generate payloads with more contextual data, an includes object may be added to the specification: &#x60;&#x60;&#x60; {   \&quot;options\&quot;: {     \&quot;filters\&quot;: {       \&quot;fromSources\&quot;: [         \&quot;client\&quot;       ],       \&quot;dataTypes\&quot;: [         \&quot;tableData\&quot;       ],       \&quot;recordChangeScope\&quot;: \&quot;tbl00000000000000\&quot;,       \&quot;watchDataInFieldIds\&quot;: [         \&quot;fld00000000000001\&quot;,         \&quot;fld00000000000002\&quot;       ]     },     \&quot;includes\&quot;: {       \&quot;includeCellValuesInFieldIds\&quot;: [         \&quot;fld00000000000000\&quot;       ]     }   } } &#x60;&#x60;&#x60;
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WebhooksSpecificationIncludes implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Webhooks_specification_includes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'include_cell_values_in_field_ids' => '\Ez128\Airtable\Model\WebhooksSpecificationIncludesIncludeCellValuesInFieldIds',
        'include_previous_cell_values' => 'bool',
        'include_previous_field_definitions' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'include_cell_values_in_field_ids' => null,
        'include_previous_cell_values' => null,
        'include_previous_field_definitions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'include_cell_values_in_field_ids' => false,
        'include_previous_cell_values' => false,
        'include_previous_field_definitions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'include_cell_values_in_field_ids' => 'includeCellValuesInFieldIds',
        'include_previous_cell_values' => 'includePreviousCellValues',
        'include_previous_field_definitions' => 'includePreviousFieldDefinitions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'include_cell_values_in_field_ids' => 'setIncludeCellValuesInFieldIds',
        'include_previous_cell_values' => 'setIncludePreviousCellValues',
        'include_previous_field_definitions' => 'setIncludePreviousFieldDefinitions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'include_cell_values_in_field_ids' => 'getIncludeCellValuesInFieldIds',
        'include_previous_cell_values' => 'getIncludePreviousCellValues',
        'include_previous_field_definitions' => 'getIncludePreviousFieldDefinitions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('include_cell_values_in_field_ids', $data ?? [], null);
        $this->setIfExists('include_previous_cell_values', $data ?? [], null);
        $this->setIfExists('include_previous_field_definitions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets include_cell_values_in_field_ids
     *
     * @return \Ez128\Airtable\Model\WebhooksSpecificationIncludesIncludeCellValuesInFieldIds|null
     */
    public function getIncludeCellValuesInFieldIds()
    {
        return $this->container['include_cell_values_in_field_ids'];
    }

    /**
     * Sets include_cell_values_in_field_ids
     *
     * @param \Ez128\Airtable\Model\WebhooksSpecificationIncludesIncludeCellValuesInFieldIds|null $include_cell_values_in_field_ids include_cell_values_in_field_ids
     *
     * @return self
     */
    public function setIncludeCellValuesInFieldIds($include_cell_values_in_field_ids)
    {
        if (is_null($include_cell_values_in_field_ids)) {
            throw new \InvalidArgumentException('non-nullable include_cell_values_in_field_ids cannot be null');
        }
        $this->container['include_cell_values_in_field_ids'] = $include_cell_values_in_field_ids;

        return $this;
    }

    /**
     * Gets include_previous_cell_values
     *
     * @return bool|null
     */
    public function getIncludePreviousCellValues()
    {
        return $this->container['include_previous_cell_values'];
    }

    /**
     * Sets include_previous_cell_values
     *
     * @param bool|null $include_previous_cell_values If true, include the previous cell value in the payload.
     *
     * @return self
     */
    public function setIncludePreviousCellValues($include_previous_cell_values)
    {
        if (is_null($include_previous_cell_values)) {
            throw new \InvalidArgumentException('non-nullable include_previous_cell_values cannot be null');
        }
        $this->container['include_previous_cell_values'] = $include_previous_cell_values;

        return $this;
    }

    /**
     * Gets include_previous_field_definitions
     *
     * @return bool|null
     */
    public function getIncludePreviousFieldDefinitions()
    {
        return $this->container['include_previous_field_definitions'];
    }

    /**
     * Sets include_previous_field_definitions
     *
     * @param bool|null $include_previous_field_definitions If true, include the previous field definition in the payload.
     *
     * @return self
     */
    public function setIncludePreviousFieldDefinitions($include_previous_field_definitions)
    {
        if (is_null($include_previous_field_definitions)) {
            throw new \InvalidArgumentException('non-nullable include_previous_field_definitions cannot be null');
        }
        $this->container['include_previous_field_definitions'] = $include_previous_field_definitions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


