<?php
/**
 * HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1ErrTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ez128\Airtable\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1ErrTest Class Doc Comment
 *
 * @category    Class
 * @description HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1Err
 * @package     Ez128\Airtable
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1ErrTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1Err"
     */
    public function testHyperdbUpsertRecordsByPrimaryKeys200ResponseCompressedResponseDataResultPromiseAnyOf1Err()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stack"
     */
    public function testPropertyStack()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
