<?php
/**
 * WebhooksTableCreatedTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ez128\Airtable\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WebhooksTableCreatedTest Class Doc Comment
 *
 * @category    Class
 * @description &#x60;&#x60;&#x60; {  \&quot;metadata\&quot;: {      \&quot;name\&quot;: \&quot;new table\&quot;,      \&quot;description\&quot;: \&quot;new table description\&quot;  },  \&quot;fieldsById\&quot;: {      \&quot;fld00000000000000\&quot;: {          \&quot;name\&quot;: \&quot;Name\&quot;,          \&quot;type\&quot;: \&quot;singleLineText\&quot;      },      \&quot;fld00000000000001\&quot;: {          \&quot;name\&quot;: \&quot;Description\&quot;,          \&quot;type\&quot;: \&quot;multilineText\&quot;      }  },  \&quot;recordsById\&quot;: {      \&quot;rec00000000000000\&quot;: {          \&quot;createdTime\&quot;: \&quot;2022-02-01T21:25:05.663Z\&quot;,          \&quot;cellValuesByFieldId\&quot;: {              \&quot;fld00000000000000\&quot;: \&quot;Hello\&quot;,              \&quot;fld00000000000001\&quot;: \&quot;World\&quot;          }      }  } &#x60;&#x60;&#x60;
 * @package     Ez128\Airtable
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WebhooksTableCreatedTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebhooksTableCreated"
     */
    public function testWebhooksTableCreated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fields_by_id"
     */
    public function testPropertyFieldsById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "records_by_id"
     */
    public function testPropertyRecordsById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
