<?php
/**
 * AuditingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ez128\Airtable\Test\Api;

use \Ez128\Airtable\Configuration;
use \Ez128\Airtable\ApiException;
use \Ez128\Airtable\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AuditingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAuditLogRequest
     *
     * Create audit log request.
     *
     */
    public function testCreateAuditLogRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAuditLogRequest
     *
     * Get audit log request.
     *
     */
    public function testGetAuditLogRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAuditLogRequests
     *
     * List audit log requests.
     *
     */
    public function testListAuditLogRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
