<?php
/**
 * CollaboratorsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Airtable API
 *
 * The Airtable REST API. Please see https://airtable.com/developers/ for more details.
 *
 * The version of the OpenAPI document: 0
 * Contact: help@airtable.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ez128\Airtable\Test\Api;

use \Ez128\Airtable\Configuration;
use \Ez128\Airtable\ApiException;
use \Ez128\Airtable\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CollaboratorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ez128\Airtable
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CollaboratorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addBaseCollaborator
     *
     * Add base collaborator.
     *
     */
    public function testAddBaseCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addInterfaceCollaborator
     *
     * Add interface collaborator.
     *
     */
    public function testAddInterfaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addWorkspaceCollaborator
     *
     * Add workspace collaborator.
     *
     */
    public function testAddWorkspaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteBaseCollaborator
     *
     * Delete base collaborator.
     *
     */
    public function testDeleteBaseCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteInterfaceCollaborator
     *
     * Delete interface collaborator.
     *
     */
    public function testDeleteInterfaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWorkspaceCollaborator
     *
     * Delete workspace collaborator.
     *
     */
    public function testDeleteWorkspaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBaseCollaborators
     *
     * Get base collaborators.
     *
     */
    public function testGetBaseCollaborators()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInterface
     *
     * Get interface.
     *
     */
    public function testGetInterface()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWorkspaceCollaborators
     *
     * Get workspace collaborators.
     *
     */
    public function testGetWorkspaceCollaborators()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCollaboratorBasePermission
     *
     * Update collaborator base permission.
     *
     */
    public function testUpdateCollaboratorBasePermission()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateInterfaceCollaborator
     *
     * Update interface collaborator.
     *
     */
    public function testUpdateInterfaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkspaceCollaborator
     *
     * Update workspace collaborator.
     *
     */
    public function testUpdateWorkspaceCollaborator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
